/**
 * Types for `battle_stats.json` (generated by data/export_battle_stats.py).
 *
 * Two value shapes: pair/combo maps store `StatEntry` (no `total` — code computes
 * `wins + losses`); single-entity maps store `EntityStat` (with `total`).
 * Composite key formats are defined by `src/services/statKeys.ts`.
 */

export interface StatEntry {
  wins: number;
  losses: number;
  wilson: number;
}

export interface EntityStat extends StatEntry {
  total: number;
}

/** One synergy row; the name field is `partner` for heroes, `hero` for skills. */
interface SynergyBase {
  pair_wilson: number;
  without_wilson: number;
  synergy_boost: number;
  game_share: number;
}

export interface SynergyPartner extends SynergyBase {
  partner: string;
}

export interface SynergyHero extends SynergyBase {
  hero: string;
}

export interface HeroSynergy {
  has_significant_synergy: boolean;
  synergy_partners: SynergyPartner[];
}

export interface SkillSynergy {
  has_significant_synergy: boolean;
  synergy_heroes: SynergyHero[];
}

export interface BattleStats {
  hero_stats: Record<string, EntityStat>;
  skill_stats: Record<string, EntityStat>;
  hero_combinations: Record<string, StatEntry>;
  hero_pair_stats: Record<string, StatEntry>;
  skill_pair_stats: Record<string, StatEntry>;
  /** Key is `"hero,skill"` (hero first, NOT sorted). */
  skill_hero_pair_stats: Record<string, StatEntry>;
  hero_synergy_stats: Record<string, HeroSynergy>;
  skill_synergy_stats: Record<string, SkillSynergy>;
  total_battles: number;
  team1_wins: number;
  team2_wins: number;
  unknown_wins: number;
  generated_at: string;
  previous_total_battles: number;
  added_battles: number;
}
