/**
 * Types for `recommendation_data.json` — the offline artifact generated by
 * `data/build_recommendation_data.py`.
 *
 * The web app imports this artifact once and performs all
 * scoring/optimization locally against the learned paired model. See
 * `web/src/services/recommendationEngine.ts` for the scoring logic and
 * README.md "Recommendation pipeline" for the end-to-end design.
 */

/** Feature-family prefixes used in the flat weight/support maps. */
export type FeatureFamily = 'H' | 'S' | 'HP' | 'HS' | 'SP';

export interface RecommendationSchema {
  version: number;
  model_type: string;
  feature_families: Record<string, string>;
  default_skill_index: number;
}

export interface RecommendationCatalog {
  catalog_version: string;
  hero_count: number;
  skill_count: number;
  /** hero name → its default (signature) skill; that skill is not a draftable feature. */
  default_skill: Record<string, string>;
}

export interface BattleCounts {
  total_battles: number;
  team1_wins: number;
  team2_wins: number;
  invalid_battles: number;
  /**
   * Deterministic content hash of the validated training corpus. Identifies the
   * battles the artifact was built from without any wall-clock timestamp — the
   * artifact is byte-reproducible, so there is no `generated_at`/`added_battles`.
   */
  corpus_version: string;
}

export interface AtomicWeightComponent {
  /** Regularized paired-logistic outcome coefficient before the count prior. */
  outcome_weight: number;
  /** Symmetric season-aware player-selection adjustment. */
  count_adjustment: number;
  /** Exact value emitted in `weights`. */
  final_weight: number;
  /** Known-season team appearances (mirror matches count once per side). */
  appearance_count: number;
  /** Uniform expected appearances after catalog-season availability adjustment. */
  expected_count: number;
  /** `appearance_count / expected_count`, or zero when there was no exposure. */
  usage_ratio: number;
}

export interface SelectionPriorMetadata {
  hero_strength: number;
  skill_strength: number;
  smoothing: number;
  log_ratio_clip: number;
  hero_slots_per_battle: number;
  skill_slots_per_battle: number;
  count_unit: string;
  expected_count: string;
}

export interface PairedModel {
  intercept: number;
  l2_C: number;
  min_support_single: number;
  min_support_pair: number;
  n_features: number;
  /** Final outcome-plus-selection weights used for roster scoring. */
  weights: Record<string, number>;
  /** feature id → number of battles it appeared in (evidence/support). */
  support: Record<string, number>;
  selection_prior?: SelectionPriorMetadata;
  /** Transparent decomposition for emitted atomic H/S weights. */
  atomic_components?: Record<string, AtomicWeightComponent>;
}

export interface AnalyticsRow {
  name: string;
  wins: number;
  losses: number;
  total: number;
  win_rate: number;
  smoothed_win_rate: number;
  /** Number of observations explicitly carrying upstream 影 provenance. */
  shadow_total?: number;
}

export interface RecommendationAnalytics {
  prior_win_rate: number;
  heroes: AnalyticsRow[];
  skills: AnalyticsRow[];
}

export interface BacktestMetrics {
  n_train?: number;
  n_test: number;
  accuracy: number | null;
  log_loss: number | null;
  brier: number | null;
  holdout_frac: number;
  baseline_accuracy?: number;
  note?: string;
}

export interface RecommendationData {
  schema: RecommendationSchema;
  catalog: RecommendationCatalog;
  battle_counts: BattleCounts;
  model: PairedModel;
  analytics: RecommendationAnalytics;
  backtest: BacktestMetrics;
}
