/**
 * Types for `recommendation_data.json` — the offline artifact generated by
 * `data/build_recommendation_data.py`.
 *
 * The web app imports this artifact once and performs all
 * scoring/optimization locally against the learned paired model. See
 * `web/src/services/recommendationEngine.ts` for the scoring logic and
 * README.md "Recommendation pipeline" for the end-to-end design.
 */

/** Feature-family prefixes used in the flat weight/support maps. */
export type FeatureFamily =
  | 'H'
  | 'S'
  | 'HP'
  | 'HS'
  | 'SP'
  | 'THS'
  | 'TSP'
  | 'HT'
  | 'TS3'
  | 'HC'
  | 'B'
  | 'M';

export interface RecommendationSchema {
  version: number;
  model_type: string;
  feature_families: Record<string, string>;
  default_skill_index: number;
}

export interface BondRelationship {
  name: string;
  required_members: 2 | 3;
  /** Canonically sorted validated hero names. */
  members: string[];
}

export interface RecommendationRelationships {
  /** Hero name → camp used by exclusive HC|2 / HC|3 scoring. */
  hero_camp: Record<string, string>;
  /** Identity-only activation contracts; effect text is intentionally absent. */
  bonds: BondRelationship[];
}

export type MechanicRelation =
  | 'provides'
  | 'benefits_from'
  | 'requires'
  | 'consumes';

export type MechanicSubject =
  | 'self'
  | 'ally'
  | 'team'
  | 'enemy'
  | 'any'
  | 'unknown';

export interface ScoringMechanicRelationship {
  relation: MechanicRelation;
  mechanic: string;
  subject: MechanicSubject;
}

export interface RecommendationMechanics {
  certainty_mode: 'explicit_only' | 'all_reviewed';
  mechanic_names: Record<string, string>;
  skills: Record<string, ScoringMechanicRelationship[]>;
}

export interface RecommendationCatalog {
  catalog_version: string;
  /** Hash of the camp map and serialized identity-only bond contracts. */
  relationship_version: string;
  /** Hash of the minimal reviewed mechanic scoring contract. */
  mechanics_version: string;
  /** Minimal reviewed mechanics used by browser M extraction. */
  mechanics: RecommendationMechanics;
  hero_count: number;
  skill_count: number;
  /** hero name → its default (signature) skill; that skill is not a draftable feature. */
  default_skill: Record<string, string>;
  relationships: RecommendationRelationships;
}

export interface BattleCounts {
  total_battles: number;
  team1_wins: number;
  team2_wins: number;
  invalid_battles: number;
  /**
   * Deterministic content hash of the validated training corpus. Identifies the
   * battles the artifact was built from without any wall-clock timestamp — the
   * artifact is byte-reproducible, so there is no `generated_at`/`added_battles`.
   */
  corpus_version: string;
}

export interface AppearanceWeightComponent {
  /** Regularized paired-logistic outcome coefficient before appearance scoring. */
  outcome_weight: number;
  /** Independently inspectable season-aware appearance adjustment. */
  count_adjustment: number;
  /** Exact outcome-plus-adjustment value emitted in `weights`; the sum is not clamped. */
  final_weight: number;
  /** Known-season concrete-team appearances (mirror matches count once per side). */
  appearance_count: number;
  /** Family-specific season-aware expected appearance count. */
  expected_count: number;
  /** `appearance_count / expected_count`, or zero when there was no exposure. */
  usage_ratio: number;
}

/** Backward-compatible name for the established H/S component contract. */
export type AtomicWeightComponent = AppearanceWeightComponent;

export interface SelectionPriorMetadata {
  hero_strength: number;
  skill_strength: number;
  hero_pair_strength: number;
  hero_skill_strength: number;
  smoothing: number;
  log_ratio_clip: number;
  hero_slots_per_battle: number;
  skill_slots_per_battle: number;
  count_unit: string;
  expected_count: string;
  relationship_count_unit: string;
  relationship_adjustment: string;
  relationship_families: Array<'HP' | 'HS'>;
  hero_pair_expected_count: string;
  hero_skill_expected_count: string;
}

export interface PairedModel {
  intercept: number;
  l2_C: number;
  min_support_single: number;
  min_support_pair: number;
  min_support_team_context: number;
  min_support_relationship: number;
  min_support_high_order: number;
  min_support_mechanic: number;
  min_mechanic_pair_diversity: number;
  team_context_shrinkage: number;
  high_order_shrinkage: number;
  mechanic_shrinkage: number;
  mech_certainty_mode: 'explicit_only' | 'all_reviewed';
  /** Hash of all browser-visible scoring semantics. */
  scoring_version: string;
  enabled_families: FeatureFamily[];
  n_features: number;
  /** Final outcome-plus-appearance weights used for roster scoring. */
  weights: Record<string, number>;
  /** feature id → number of battles it appeared in (evidence/support). */
  support: Record<string, number>;
  selection_prior?: SelectionPriorMetadata;
  /** Transparent decomposition for emitted atomic H/S weights. */
  atomic_components?: Record<string, AtomicWeightComponent>;
  /** Positive-only appearance decomposition for emitted HP/HS weights. */
  relationship_components?: Record<string, AppearanceWeightComponent>;
}

export interface AnalyticsRow {
  name: string;
  wins: number;
  losses: number;
  total: number;
  win_rate: number;
  smoothed_win_rate: number;
  /** Number of observations explicitly carrying upstream 影 provenance. */
  shadow_total?: number;
}

export interface RecommendationAnalytics {
  prior_win_rate: number;
  heroes: AnalyticsRow[];
  skills: AnalyticsRow[];
}

export interface BacktestMetrics {
  n_train?: number;
  n_test: number;
  accuracy: number | null;
  log_loss: number | null;
  brier: number | null;
  holdout_frac: number;
  baseline_accuracy?: number;
  note?: string;
}

export interface RecommendationData {
  schema: RecommendationSchema;
  catalog: RecommendationCatalog;
  battle_counts: BattleCounts;
  model: PairedModel;
  analytics: RecommendationAnalytics;
  backtest: BacktestMetrics;
}
