[build]
# Railway will use the root directory, but we'll configure the start command
# to run from the api subfolder

[deploy]
# Start command - Railway will run this from the root directory
startCommand = "python3 api/web_advisor.py"
# Health check path
healthcheckPath = "/"
# Restart policy
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
