import database from '../../public/game-data/database.json';

export const MAX_BODY_BYTES = 16 * 1024;
export const MAX_UPLOADER_NAME_CODE_POINTS = 80;
export const MAX_PENDING_SUBMISSIONS = 500;

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const INVISIBLE_CONTROL_RE = /[\p{Cc}\p{Cf}\p{Cs}\p{Zl}\p{Zp}]/u;
const ZERO_WIDTH_JOINER = '\u200d';
const BODY_KEYS = new Set(['submission_id', 'uploader_name', 'season', 'battle']);
const BATTLE_KEYS = new Set(['1', '2', 'winner']);
const HERO_KEYS = new Set(['name', 'skills']);
const FINGERPRINT_SCHEMA = 'sanmou-battle-submission-v1';
const HEROES = database.heroes;
const SKILLS = database.skills;
export const CATALOG_MAX_SEASON = [
  ...Object.values(HEROES),
  ...Object.values(SKILLS),
].reduce(
  (latest, item) =>
    Number.isInteger(item.season) && item.season >= 1
      ? Math.max(latest, item.season)
      : latest,
  1
);
const INSERT_SQL = `
  INSERT INTO web_battle_submissions (
    submission_id,
    uploader_name,
    catalog_version,
    canonical_hash,
    battle_json
  )
  SELECT ?, ?, ?, ?, ?
  WHERE (
    SELECT COUNT(*)
    FROM web_battle_submissions
  ) < ${MAX_PENDING_SUBMISSIONS}
  ON CONFLICT(submission_id) DO NOTHING
`;
const SELECT_CANONICAL_HASH_SQL = `
  SELECT canonical_hash, uploader_name, battle_json
  FROM web_battle_submissions
  WHERE submission_id = ?
  LIMIT 1
`;

const responseJson = (body, status = 200, headers = {}) =>
  Response.json(body, {
    status,
    headers: {
      'Cache-Control': 'no-store',
      'X-Content-Type-Options': 'nosniff',
      ...headers,
    },
  });

const isRecord = (value) =>
  value !== null && typeof value === 'object' && !Array.isArray(value);

const hasExactKeys = (value, expected) => {
  const keys = Object.keys(value);
  return keys.length === expected.size && keys.every((key) => expected.has(key));
};

const hasDuplicates = (items) => new Set(items).size !== items.length;

const normalizeHero = (hero) => ({
  name: hero.name,
  skills: [...hero.skills],
});

const normalizeTeam = (team) => team.map(normalizeHero);

export const canonicalBattleJson = (battle, season) =>
  JSON.stringify({
    1: normalizeTeam(battle['1']),
    2: normalizeTeam(battle['2']),
    winner: battle.winner,
    season,
  });

/**
 * Return a deterministic semantic preimage for a validated submission.
 *
 * Teams are ordered by their compact JSON representation and the winner is
 * remapped to that order. Swapping submitted team sides and the winner
 * therefore leaves the fingerprint unchanged, while hero/skill positions,
 * non-identical-team winner, and the exact optional uploader name remain
 * significant. Identical teams have no distinguishable side, so their
 * canonical winner is fixed to "1". Submission season is deliberately absent
 * so changing metadata cannot bypass semantic duplicate limits.
 */
export function canonicalFingerprintJson(submission) {
  const team1 = normalizeTeam(submission.battle['1']);
  const team2 = normalizeTeam(submission.battle['2']);
  const team1Json = JSON.stringify(team1);
  const team2Json = JSON.stringify(team2);
  const identicalTeams = team1Json === team2Json;
  const swapSides = team2Json < team1Json;
  const teams = swapSides ? [team2, team1] : [team1, team2];
  let winner = submission.battle.winner;
  if (identicalTeams) {
    winner = '1';
  } else if (swapSides) {
    winner = winner === '1' ? '2' : '1';
  }

  return JSON.stringify({
    schema: FINGERPRINT_SCHEMA,
    uploader_name: Object.hasOwn(submission, 'uploader_name')
      ? submission.uploader_name
      : null,
    teams,
    winner,
  });
}

const sha256Hex = async (text) => {
  const bytes = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return [...new Uint8Array(digest)]
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
};

export const computeCanonicalHash = (submission) =>
  sha256Hex(canonicalFingerprintJson(submission));

/**
 * Match Python's compact, sort_keys=True JSON payload for every catalog field
 * that changes draft availability. Missing optional values become JSON null;
 * an absent shadow marker has the explicit semantic default false.
 */
export function canonicalCatalogJson(catalog) {
  const heroes = catalog?.heroes ?? {};
  const skills = catalog?.skills ?? {};

  return JSON.stringify({
    heroes: Object.keys(heroes)
      .sort()
      .map((name) => ({
        default_skill: heroes[name]?.skill ?? null,
        name,
        season: heroes[name]?.season ?? null,
      })),
    skills: Object.keys(skills)
      .sort()
      .map((name) => ({
        color: skills[name]?.color ?? null,
        name,
        season: skills[name]?.season ?? null,
        shadow: skills[name]?.shadow ?? false,
      })),
  });
}

const catalogFingerprintJson = canonicalCatalogJson(database);
let catalogVersionPromise;

/**
 * Match the availability-aware catalog hash generated by the Python builders.
 */
export function getCatalogVersion() {
  catalogVersionPromise ??= sha256Hex(catalogFingerprintJson).then((hash) =>
    hash.slice(0, 12)
  );
  return catalogVersionPromise;
}

const validateTeam = (team, teamKey, season) => {
  if (!Array.isArray(team) || team.length !== 3) {
    return `battle.${teamKey} must contain exactly three heroes`;
  }

  const heroNamesInTeam = [];
  const skillNamesInTeam = [];

  for (let heroIndex = 0; heroIndex < team.length; heroIndex += 1) {
    const hero = team[heroIndex];
    const path = `battle.${teamKey}[${heroIndex}]`;
    if (!isRecord(hero) || !hasExactKeys(hero, HERO_KEYS)) {
      return `${path} must contain only name and skills`;
    }
    if (typeof hero.name !== 'string' || !Object.hasOwn(HEROES, hero.name)) {
      return `${path}.name is not in the hero catalog`;
    }
    const heroSeason = HEROES[hero.name].season;
    if (
      heroSeason !== undefined &&
      (!Number.isInteger(heroSeason) || heroSeason > season)
    ) {
      return `${path}.name is not available in season ${season}`;
    }
    if (
      !Array.isArray(hero.skills) ||
      hero.skills.length !== 3 ||
      !hero.skills.every((skill) => typeof skill === 'string')
    ) {
      return `${path}.skills must contain exactly three skill names`;
    }
    if (hero.skills.some((skill) => !Object.hasOwn(SKILLS, skill))) {
      return `${path}.skills contains a skill outside the catalog`;
    }
    if (
      hero.skills.some((skill) => {
        const skillSeason = SKILLS[skill].season;
        return (
          skillSeason !== undefined &&
          (!Number.isInteger(skillSeason) || skillSeason > season)
        );
      })
    ) {
      return `${path}.skills contains a skill unavailable in season ${season}`;
    }
    if (hero.skills[0] !== HEROES[hero.name].skill) {
      return `${path}.skills[0] must be the hero's signature skill`;
    }

    heroNamesInTeam.push(hero.name);
    skillNamesInTeam.push(...hero.skills);
  }

  if (hasDuplicates(heroNamesInTeam)) {
    return `battle.${teamKey} contains duplicate heroes`;
  }
  if (hasDuplicates(skillNamesInTeam)) {
    return `battle.${teamKey} contains duplicate skills`;
  }

  return null;
};

/**
 * Validate the exact public upload contract. Returns a short client-safe error
 * or null. The handler is intentionally write-only.
 */
export function validateBattleSubmission(submission) {
  if (!isRecord(submission)) return 'request body must be an object';

  const bodyKeys = Object.keys(submission);
  if (bodyKeys.some((key) => !BODY_KEYS.has(key))) {
    return 'request body has unexpected fields';
  }
  if (
    !Object.hasOwn(submission, 'submission_id') ||
    !Object.hasOwn(submission, 'uploader_name') ||
    !Object.hasOwn(submission, 'season') ||
    !Object.hasOwn(submission, 'battle')
  ) {
    return 'request body is missing required fields';
  }
  if (
    typeof submission.submission_id !== 'string' ||
    !UUID_RE.test(submission.submission_id)
  ) {
    return 'submission_id must be a UUID';
  }
  if (
    !Number.isInteger(submission.season) ||
    submission.season < 1 ||
    submission.season > CATALOG_MAX_SEASON
  ) {
    return `season must be an integer between 1 and ${CATALOG_MAX_SEASON}`;
  }

  if (typeof submission.uploader_name !== 'string') {
    return 'uploader_name must be a string';
  }
  if ([...submission.uploader_name].length > MAX_UPLOADER_NAME_CODE_POINTS) {
    return `uploader_name must be at most ${MAX_UPLOADER_NAME_CODE_POINTS} characters`;
  }
  if (
    INVISIBLE_CONTROL_RE.test(
      submission.uploader_name.replaceAll(ZERO_WIDTH_JOINER, '')
    )
  ) {
    return 'uploader_name contains invisible control characters';
  }

  if (!isRecord(submission.battle) || !hasExactKeys(submission.battle, BATTLE_KEYS)) {
    return 'battle must contain only teams 1, 2, and winner';
  }
  if (submission.battle.winner !== '1' && submission.battle.winner !== '2') {
    return 'battle.winner must be "1" or "2"';
  }

  return (
    validateTeam(submission.battle['1'], '1', submission.season) ||
    validateTeam(submission.battle['2'], '2', submission.season)
  );
}

const readBodyWithLimit = async (request) => {
  if (!request.body) return '';

  const reader = request.body.getReader();
  const decoder = new TextDecoder('utf-8', { fatal: true });
  let totalBytes = 0;
  let text = '';

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      totalBytes += value.byteLength;
      if (totalBytes > MAX_BODY_BYTES) {
        await reader.cancel();
        return null;
      }
      text += decoder.decode(value, { stream: true });
    }
    return text + decoder.decode();
  } finally {
    reader.releaseLock();
  }
};

export async function onRequestPost({ request, env }) {
  if (!env?.TELEMETRY_DB) {
    return responseJson({ ok: false, error: 'battle storage unavailable' }, 503);
  }

  const mediaType = request.headers
    .get('content-type')
    ?.split(';', 1)[0]
    .trim()
    .toLowerCase();
  if (mediaType !== 'application/json') {
    return responseJson(
      { ok: false, error: 'content-type must be application/json' },
      415
    );
  }

  const requestOrigin = new URL(request.url).origin;
  const suppliedOrigin = request.headers.get('origin');
  if (suppliedOrigin !== null && suppliedOrigin !== requestOrigin) {
    return responseJson(
      { ok: false, error: 'cross-origin requests are not allowed' },
      403
    );
  }

  const declaredLength = Number(request.headers.get('content-length'));
  if (Number.isFinite(declaredLength) && declaredLength > MAX_BODY_BYTES) {
    return responseJson({ ok: false, error: 'request body is too large' }, 413);
  }

  let rawBody;
  try {
    rawBody = await readBodyWithLimit(request);
  } catch {
    return responseJson({ ok: false, error: 'request body must be valid JSON' }, 400);
  }
  if (rawBody === null) {
    return responseJson({ ok: false, error: 'request body is too large' }, 413);
  }

  let submission;
  try {
    submission = JSON.parse(rawBody);
  } catch {
    return responseJson({ ok: false, error: 'request body must be valid JSON' }, 400);
  }

  const validationError = validateBattleSubmission(submission);
  if (validationError) {
    return responseJson({ ok: false, error: validationError }, 400);
  }

  try {
    const uploaderName = submission.uploader_name;
    const [catalogVersion, canonicalHash] = await Promise.all([
      getCatalogVersion(),
      computeCanonicalHash(submission),
    ]);
    const battleJson = canonicalBattleJson(
      submission.battle,
      submission.season
    );
    const result = await env.TELEMETRY_DB.prepare(INSERT_SQL)
      .bind(
        submission.submission_id,
        uploaderName,
        catalogVersion,
        canonicalHash,
        battleJson
      )
      .run();
    if (Number(result?.meta?.changes) > 0) {
      return responseJson({
        ok: true,
        accepted: 1,
        duplicates: 0,
      });
    }

    const existing = await env.TELEMETRY_DB.prepare(SELECT_CANONICAL_HASH_SQL)
      .bind(submission.submission_id)
      .first();
    if (
      !existing ||
      typeof existing.canonical_hash !== 'string' ||
      (existing.uploader_name !== null &&
        typeof existing.uploader_name !== 'string') ||
      typeof existing.battle_json !== 'string'
    ) {
      if (!existing) {
        return responseJson(
          {
            ok: false,
            error: '今日待处理战报已满，请在每日更新后重试。',
          },
          429,
          { 'Retry-After': '86400' }
        );
      }
      throw new Error('D1 conflict row could not be read');
    }
    if (
      existing.canonical_hash !== canonicalHash ||
      existing.uploader_name !== uploaderName ||
      existing.battle_json !== battleJson
    ) {
      return responseJson(
        {
          ok: false,
          error: 'submission_id was already used for different content',
        },
        409
      );
    }

    return responseJson({
      ok: true,
      accepted: 0,
      duplicates: 1,
    });
  } catch (error) {
    console.error('Failed to store battle submission', error);
    return responseJson({ ok: false, error: 'battle storage unavailable' }, 503);
  }
}
